version: '3.8'
services:
  nginx:
    build:
      context: docker/nginx/
      dockerfile: Dockerfile
    ports:
      - "8080:80"   # Map host port 8080 to container port 80
      - "8443:443"  # Map host port 8443 to container port 443
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/SpeedCart/API
    expose:
      - "9000"
