version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: velocities/mynginx:latest  # Use the remote image
    volumes:
      - /etc/nginx/ssl:/var/www/SpeedCart/API/docker/nginx/ssl # All containers use the same SSL data
    ports:
      - "8080:80"   # Map host port 8080 to container port 80
      - "8443:443"  # Map host port 8443 to container port 443
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: velocities/myapp:latest  # Use the remote image
    volumes:
      - ./database:/var/www/SpeedCart/API/database
      - ./storage:/var/www/SpeedCart/API/storage
      - ./bootstrap/cache:/var/www/SpeedCart/API/bootstrap/cache
    expose:
      - "9000"
