version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/SpeedCart/API
    volumes:
      - .:/var/www/SpeedCart/API
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    # Map host ports to ports in container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/SpeedCart/API
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  laravel:
    driver: bridge
