name: Backend Deployment

on:
  push:
    paths:
      - 'API/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Adjust PHP version as needed

    - name: Install Composer dependencies
      run: |
        cd API  # Assuming your Laravel app directory is 'API'
        composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Clear caches and perform other Laravel tasks
      run: |
        cd API
        php artisan optimize:clear
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push nginx image
      run: |
        cd API
        docker-compose build nginx
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/mynginx:latest ${{ secrets.DOCKER_HUB_USERNAME }}/mynginx:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mynginx:latest

    - name: Build and push app image
      run: |
        cd API
        docker-compose build app
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        script: |
          cd ${{ secrets.DOCKER_COMPOSE_DIRECTORY }}
          docker-compose pull
          docker-compose up -d
