name: Backend Deployment

on:
  # Allows manual deployment
  workflow_dispatch:
  push:
    # Triggers only when code is pushed to the development branch
    # that modifies files in the API directory
    branches:
      - deployment  # production
      - development # development

    paths:
      - 'API/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # If the branch is deployment, tag the image with prod (otherwise, tag it with dev)
        tags: |
          ${{ secrets.IMAGE_NAME }}:${{ github.ref == 'refs/heads/deployment' && 'prod' || 'dev' }}

  trigger-do-deployment:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger DigitalOcean App Platform redeploy
        # We have two apps, one for prod and one for dev
        run: |
          APP_ID=${{ github.ref == 'refs/heads/deployment' && secrets.DO_APP_ID_PROD || secrets.DO_APP_ID_DEV }}
          curl -X POST "https://api.digitalocean.com/v2/apps/$APP_ID/deployments" \
          -H "Authorization: Bearer ${{ secrets.DO_API_TOKEN }}"
