name: Frontend Deployment

on:
  # Allows manual deployment
  workflow_dispatch:
  push:
    # Triggers only when code is pushed to the deployment or development branches
    # that modifies files in the Frontend or docs/legal directories
    branches:
      - deployment
      - development

    paths:
      - 'Frontend/**'
      - 'docs/legal/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.6.0'

    - name: Install dependencies
      run: cd Frontend && npm install --force # This should install all dependencies, regardless of the workspace
    
    - name: Write shared .env file
      run: echo "${{ github.ref == 'refs/heads/deployment' && secrets.SHARED_PROD_ENV_FILE || secrets.SHARED_DEV_ENV_FILE }}" > Frontend/shared/.env

    - name: Write Frontend .env file
      run: echo "${{ github.ref == 'refs/heads/deployment' && secrets.FRONTEND_PROD_ENV_FILE || secrets.FRONTEND_DEV_ENV_FILE }}" > Frontend/speedcart-react/.env

    - name: Build front end
      env:
        CI: false
      run: cd Frontend && npm run build # This makes sure the build succeeds before running it on the production server
    
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CF_PAGES_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        projectName: "${{ github.ref == 'refs/heads/deployment' && 'speedcart' || 'speedcart-dev' }}"
        directory: "Frontend/speedcart-react/build"
        branch: "${{ github.ref == 'refs/heads/deployment' && 'deployment' || 'development' }}"