name: Frontend Deployment

on:
  push:
    paths:
      - 'Frontend/**'
      - 'docs/legal/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.6.0'

    - name: Install dependencies
      run: cd Frontend && npm install --force # This should install all dependencies, regardless of the workspace

    - name: Build front end
      env:
        CI: false
      run: cd Frontend && npm run build # This makes sure the build succeeds before running it on the production server
    
    # Compress the build folder
    - name: Archive build folder
      run: |
        cd Frontend/speedcart-react
        tar -czf build.tar.gz build/

    - name: Install SSH Key and Configure Access
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    
    # Transfer the build to the server
    - name: Upload build to server
      run: |
        scp -i ~/.ssh/id_rsa build.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/Frontend

    # Deploy on the server
    - name: Deploy build on server
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd ${{ secrets.WORK_DIR }}/Frontend
        tar -xzf build.tar.gz
        rm -f build.tar.gz