name: Frontend Deployment

on:
  push:
    paths:
      - 'speedcart-react/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.6.0'

    - name: Install dependencies
      run: cd speedcart-react && npm install

    - name: Build front end
      run: cd speedcart-react && ./build.sh

    - name: Deploy front end
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        echo "$SSH_PRIVATE_KEY" > id_rsa
        chmod 600 id_rsa
        mkdir -p ~/.ssh
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        rsync -avz -e "ssh -i id_rsa -o StrictHostKeyChecking=no" --delete-after speedcart-react/build/ your_user@your_server:/path/to/your/web/root
        rm -f id_rsa